// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://viuclcnolqdfezwcyolg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpdWNsY25vbHFkZmV6d2N5b2xnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNjA5OTYsImV4cCI6MjA3NDYzNjk5Nn0.ko7p76HRrl9DA0P5ZNKfzM3V7_zrQ9GjBJmyKmu5WXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);